### ISSUE TITLE
throw new Error('The dialect ' + this.getDialect() + ' is not supported. (

### ISSUE THREAD

**Issue by sunnyhub** [phodal/lan#8]
一直卡在这个位置，求大神帮忙解答下，非常感谢

> lan@0.1.0 start /Users/sonny/lan
> node server.js

/Users/sonny/lan/node_modules/sequelize/lib/sequelize.js:183
    throw new Error('The dialect ' + this.getDialect() + ' is not supported. (
          ^
Error: The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)
    at new Sequelize (/Users/sonny/lan/node_modules/sequelize/lib/sequelize.js:183:11)
    at Object.<anonymous> (/Users/sonny/lan/models/index.js:9:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sonny/lan/server/index.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sonny/lan/app.js:8:14)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! lan@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lan@0.1.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the lan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sonny/lan/config/npm-debug.log

**Comment by phodal** [comment]
试试

    npm install sqlite3

http://stackoverflow.com/questions/18291476/connect-sequelize-js-to-node-webkit-desktop-app-using-sqlite

**Comment by sunnyhub** [comment]
OK 了非常感谢！！
